import type { NotificationService } from 'src/modules/notification/notification.service';

export const HELP_TEXT = [
  '🤖 *OpenCode Bot*',
  '',
  'Just type a prompt to start an interactive session.',
  'Output streams live to Telegram.',
  '',
  '*Session*',
  '/session <prompt> — Start session',
  '/send <text> — Send text to active session',
  '/sessions — List / switch sessions',
  '/cancel — Cancel session',
  '',
  '*Terminal Keys*',
  '/tab — Tab (autocomplete)',
  '/enter — Enter (confirm)',
  '/up — Arrow Up',
  '/down — Arrow Down',
  '/ctrl_c — Interrupt (Ctrl+C)',
  '',
  '*OpenCode Control*',
  '/model <name> — Switch model (in-session)',
  '/skill <name> — Load skill (in-session)',
  '/opencode <args> — Send text to active session (alias for /send)',
  '',
  '*Setup*',
  '/setup — Open workspace Settings hub',
  '',
  '*Git Credentials*',
  '/git login <user> <token> [url] — Set git credentials',
  '  Example: /git login alice ghp_xxx https://github.com/org/repo.git',
  '/git logout — Remove credentials',
  '/git credential-status — Show credential info',
  '/git test — Re-validate credentials',
  '',
  '*Git Operations (on active project)*',
  '/git status — Show repo status (branch, changes)',
  '/git diff — Show unstaged changes',
  '/git add — Stage all changes',
  '/git commit <msg> — Commit staged changes',
  '/git push — Push to remote',
  '/git pull — Pull from remote',
  '/git log — Show recent commits',
  '/git pr — Create PR with gh CLI',
  '',
  '*Workspace (manage via Settings)*',
  '/workspace create <name> — Create workspace',
  '/workspace list — List workspaces',
  '/workspace switch <name> — Switch active workspace',
  '/workspace show — Show workspace Settings',
  '/workspace provider <id> <key> — Set AI provider',
  '/workspace models <provider> — List models',
  '/workspace model <provider/model> — Set default model',
  '/workspace sync <name> — Sync git projects',
  '',
  '*Project*',
  '/project add <name> <path> [url] — Add git project',
  '/project list — List projects',
  '/project edit <name> (name:|path:) — Edit project',
  '/project delete <name> — Delete project',
  '/project branches <name> — List branches',
  '/project switch <name> <branch> — Switch branch',
  '/project install <name> — Install dependencies',
].join('\n');

const CONTEXTUAL_HELP: Record<string, string> = {
  'workspace-list': [
    '📋 *Workspaces Help*',
    '',
    'Each workspace row shows:',
    '• ✅ Active workspace',
    '• 🔵🟢🟣⚫ Provider indicator',
    '• 🤖 Model name (short)',
    '• 📁 Project count',
    '• 🔑✓ / 🔑✗ Git status',
    '',
    'Tap a workspace to open its Settings.',
    'Tap ➕ New Workspace to create one.',
    '',
    'Shortcuts: /workspace list, /workspace switch <name>',
  ].join('\n'),
  'settings': [
    '⚙️ *Settings Help*',
    '',
    'This is the command center for your workspace.',
    '',
    '• *Change Provider* — Select AI provider and enter API key',
    '• *Change Model* — Pick the default model (paginated list)',
    '• *Manage Projects* — View, add, or remove git projects',
    '• *Manage Git* — View git credential status, log out',
    '• *Sessions* — View session count, start new session',
    '',
    'Each section opens a sub-screen. Tap 🔙 Settings to return.',
    '',
    'You can also use slash commands like /workspace provider.',
  ].join('\n'),
  'model-picker': [
    '🤖 *Model Picker Help*',
    '',
    'Browse available models page by page.',
    '• Tap a model to set it as the default for this workspace',
    '• Use ◀ Prev / Next ▶ to navigate pages',
    '• Page X/Y shows your current position',
    '',
    'The model is set at workspace level — all sessions',
    'in this workspace use the same default model.',
    '',
    'Tap 🔙 Settings to return without changing.',
  ].join('\n'),
  'provider-picker': [
    '🔵 *Provider Help*',
    '',
    'Choose an AI provider:',
    '• OpenCode Zen/Go — opencode.ai',
    '• OpenAI — platform.openai.com',
    '• Anthropic Claude — console.anthropic.com',
    '• GitHub Copilot — github.com/copilot',
    '',
    'After selecting, you will be prompted to enter',
    'your API key as a text message.',
    '',
    'The API key is stored per-workspace and never',
    'baked into the Docker container.',
  ].join('\n'),
  'project-list': [
    '📁 *Projects Help*',
    '',
    'Projects are git repositories in this workspace.',
    '• Tap a project to see git status, diff, commit, push',
    '• Tap 🗑️ to remove a project',
    '• Tap ➕ Add Project to add a new repository',
    '',
    'Add via: /project add <name> <path> [remote-url]',
  ].join('\n'),
  'git-manage': [
    '🔑 *Git Credentials Help*',
    '',
    'Git credentials let the bot authenticate with',
    'remote repositories for clone, pull, push, and PRs.',
    '',
    'Set via: /git login <username> <token> <remote-url>',
    'Remove via: Logout button or /git logout',
    '',
    'Credentials are stored per-workspace and injected',
    'on each docker exec — never baked into the container.',
  ].join('\n'),
  'session-list': [
    '⚡ *Sessions Help*',
    '',
    'Sessions are interactive OpenCode CLI prompts.',
    '• Send a text message to start a new session',
    '• Use /sessions to list and switch sessions',
    '• Use /cancel to cancel the active session',
    '',
    'Sessions are scoped to this workspace.',
  ].join('\n'),
};

export async function sendContextualHelp(
  chatId: string,
  screen: string,
  notificationService: NotificationService,
): Promise<void> {
  const text = CONTEXTUAL_HELP[screen];
  if (!text) {
    await notificationService.sendRaw(chatId, 'No help available for this screen.');
    return;
  }
  await notificationService.sendRaw(chatId, text);
}
