export const HELP_TEXT = [
  '🤖 *OpenCode Bot*',
  '',
  'Just type a prompt to start an interactive session.',
  'Output streams live to Telegram.',
  '',
  '*Session*',
  '/session <prompt> — Start session',
  '/send <text> — Send text to active session',
  '/sessions — List / switch sessions',
  '/cancel — Cancel session',
  '',
  '*Terminal Keys*',
  '/tab — Tab (autocomplete)',
  '/enter — Enter (confirm)',
  '/up — Arrow Up',
  '/down — Arrow Down',
  '/ctrl_c — Interrupt (Ctrl+C)',
  '',
  '*OpenCode Control*',
  '/model <name> — Switch model (in-session)',
  '/skill <name> — Load skill (in-session)',
  '/opencode <args> — Send text to active session (alias for /send)',
  '',
  '*Setup*',
  '/setup — Guided setup wizard (provider, model, git)',
  '',
  '*Git Credentials*',
  '/git login <user> <token> [url] — Set git credentials',
  '  Example: /git login alice ghp_xxx https://github.com/org/repo.git',
  '/git logout — Remove credentials',
  '/git credential-status — Show credential info',
  '/git test — Re-validate credentials',
  '',
  '*Git Operations (on active project)*',
  '/git status — Show repo status (branch, changes)',
  '/git diff — Show unstaged changes',
  '/git add — Stage all changes',
  '/git commit <msg> — Commit staged changes',
  '/git push — Push to remote',
  '/git pull — Pull from remote',
  '/git log — Show recent commits',
  '/git pr — Create PR with gh CLI',
  '',
  '*Workspace*',
  '/workspace create <name> — Create workspace',
  '/workspace list — List workspaces',
  '/workspace switch <name> — Switch active workspace',
  '/workspace show — Show active workspace details',
  '/workspace rename <old> <new> — Rename workspace',
  '/workspace delete <name> — Delete workspace',
  '/workspace provider <id> <key> — Set AI provider',
  '/workspace models <provider> — List models',
  '/workspace model <provider/model> — Set default model',
  '/workspace sync <name> — Sync git projects',
  '/workspace github-token <token> — Set git token (deprecated, use /git login)',
  '',
  '*Project*',
  '/project add <name> <path> [url] — Add git project',
  '/project list — List projects',
  '/project edit <name> (name:|path:) — Edit project',
  '/project delete <name> — Delete project',
  '/project branches <name> — List branches',
  '/project switch <name> <branch> — Switch branch',
  '/project install <name> — Install dependencies',
  '/project provider <id> <key> — Set provider (per project)',
  '/project models <provider> — List models (per project)',
  '/project model <provider/model> — Set model (per project)',
].join('\n');
